// IIFE - FUNÇÃO IMEDIATAMENTE INVOCADA

// QUANDO USAR? - QUANDO VOCÊ PRECISA GARANTIR QUE DETERMINADOS VALORES
//ESTARÃO DENTRO DE UM ESCOPO MAIS RESTRITO
(function (a, b, c) {
  console.log(`Result ${a + b + c}`);
})(2, 5, 9);
